# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

running_quantile_cpp <- function(data, adjusted_day_of_year, q, min_fraction) {
    .Call('_rIACI_running_quantile_cpp', PACKAGE = 'rIACI', data, adjusted_day_of_year, q, min_fraction)
}

