name: R-CMD-check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - { os: ubuntu-latest, r: 'release' }
          - { os: macos-latest, r: 'release' }
          - { os: windows-latest, r: 'release' }
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}

      - name: Install system dependencies (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          sudo apt-get update || brew update
          # 根据需要安装其它系统依赖

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Set RETICULATE_PYTHON environment variable
        run: echo "RETICULATE_PYTHON=$(which python)" >> $GITHUB_ENV

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install xarray pandas numpy netcdf4 dask

      - name: Install R package dependencies
        run: |
          Rscript -e "install.packages(c('testthat', 'reticulate'), repos='https://cloud.r-project.org')"

      - name: Install devtools
        run: Rscript -e "install.packages('devtools', repos='https://cloud.r-project.org')"

      - name: Install package
        run: Rscript -e "devtools::install_local()"

      - name: Run tests
        env:
          ECMWF_USER_ID: ${{ secrets.ECMWF_USER_ID }}
          ECMWF_USER_KEY: ${{ secrets.ECMWF_USER_KEY }}
        run: Rscript -e "library(testthat); test_dir('tests')"
